name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TEST_DB_host: qvti2nukhfiig51b.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
      TEST_DB_user: pe1ay0vi3znxgd40
      TEST_DB_password: ogzkbhy5mctix7rf
      TEST_DB_name: zw87sk0vg0b6bh0b

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn run test